import CryptoKit
import Darwin
import Foundation
import LensCore

/// Catalog-only replay on fixtures generated by measure-session-catalog.py.
/// All URLs are derived from a new private output; no observed Codex home is accepted.
@main struct SessionCatalogPerformanceMain {
    private static func stamp() -> UInt64 { DispatchTime.now().uptimeNanoseconds }
    private static func usage() -> rusage { var value = rusage(); getrusage(RUSAGE_SELF, &value); return value }
    private static func cpu(_ value: rusage) -> Double {
        Double(value.ru_utime.tv_sec + value.ru_stime.tv_sec)
            + Double(value.ru_utime.tv_usec + value.ru_stime.tv_usec) / 1e6
    }
    private static func digest(_ bytes: Data) -> String {
        SHA256.hash(data: bytes).map { String(format: "%02x", $0) }.joined()
    }
    private static func physicalPath(_ path: String) throws -> String {
        guard let resolved = path.withCString({ Darwin.realpath($0, nil) }) else {
            throw LensError.unavailable("Benchmark path cannot be resolved.")
        }
        defer { free(resolved) }
        return String(cString: resolved)
    }
    private static func emit(_ value: [String: Any]) throws {
        let bytes = try JSONSerialization.data(withJSONObject: value, options: [.sortedKeys])
        print(String(decoding: bytes, as: UTF8.self)); fflush(stdout)
    }
    private static func rejectFixtureLinks(in home: URL) throws {
        if let files = FileManager.default.enumerator(at: home, includingPropertiesForKeys: [.isSymbolicLinkKey]) {
            for case let file as URL in files where try file.resourceValues(forKeys: [.isSymbolicLinkKey]).isSymbolicLink == true {
                throw LensError.unsupported("Fixture links are not accepted.")
            }
        }
    }
    private static func measure(_ engine: SessionEngine, home: URL, label: String, sample: Int) async throws {
        let before = usage(), started = stamp()
        let summaries = try await engine.catalog()
        let elapsed = Double(stamp() - started) / 1e6, after = usage()
        let encoder = JSONEncoder(); encoder.outputFormatting = [.sortedKeys]
        var portable = summaries
        let prefixes = Set([home.path, home.standardizedFileURL.path, try physicalPath(home.path)])
            .map { $0 + "/" }.sorted { $0.count > $1.count }
        for index in portable.indices {
            portable[index].paths = portable[index].paths.map {
                if let prefix = prefixes.first(where: $0.hasPrefix) {
                    return "fixture/" + String($0.dropFirst(prefix.count))
                }
                return $0
            }
        }
        var relations: [String: Int] = [:]
        for summary in summaries { relations[summary.relation.rawValue, default: 0] += 1 }
        try emit(["label": label, "sample": sample, "elapsed_ms": elapsed,
                  "cpu_ms": (cpu(after) - cpu(before)) * 1000, "peak_rss_bytes": after.ru_maxrss,
                  "summaries": summaries.count, "relation_counts": relations,
                  "summary_sha256": digest(try encoder.encode(summaries)),
                  "portable_summary_sha256": digest(try encoder.encode(portable)),
                  "indexed_titles": summaries.filter { $0.title.hasPrefix("Indexed anonymous session ") }.count,
                  "session_ids": Set(summaries.map(\.sessionID)).count])
    }
    private static func run() async throws {
        guard CommandLine.arguments.count == 2 else {
            throw LensError.unsupported("Use scripts/measure-session-catalog.py with a new private output.")
        }
        guard CommandLine.arguments[1].hasPrefix("/") else {
            throw LensError.unsupported("An absolute private benchmark output is required.")
        }
        let outputPath = try physicalPath(CommandLine.arguments[1])
        let rootComponents = try physicalPath("/private/tmp").split(separator: "/")
        let outputComponents = outputPath.split(separator: "/")
        let output = URL(fileURLWithPath: outputPath, isDirectory: true)
        // Foundation standardization can present /private/tmp as /tmp. Compare
        // physical components so aliases work and symlink escapes still fail.
        guard outputComponents.count > rootComponents.count, outputComponents.starts(with: rootComponents),
              let permissions = try FileManager.default.attributesOfItem(atPath: outputPath)[.posixPermissions] as? NSNumber,
              permissions.intValue & 0o077 == 0 else {
            throw LensError.unsupported("A private, resident output under /private/tmp is required.")
        }
        let manifest = try JSONSerialization.jsonObject(with: Data(contentsOf:
            output.appendingPathComponent("fixture-manifest.json"))) as? [String: Any]
        guard manifest?["anonymous_session_catalog_fixture"] as? Bool == true,
              manifest?["schema_version"] as? Int == 1 else {
            throw LensError.unsupported("Missing generated anonymous fixture manifest.")
        }
        let home = output.appendingPathComponent("fixture", isDirectory: true)
        guard try physicalPath(home.path) == outputPath + "/fixture" else {
            throw LensError.unsupported("Fixture links are not accepted.")
        }
        try rejectFixtureLinks(in: home)
        let caches = output.appendingPathComponent("caches", isDirectory: true)
        for name in ["first", "fresh-1", "fresh-2", "fresh-3"] where
            FileManager.default.fileExists(atPath: caches.appendingPathComponent(name).path) {
            throw LensError.unsupported("Existing benchmark caches are not accepted; create a new replay.")
        }
        func engine(_ name: String) -> SessionEngine {
            SessionEngine(home: home, cacheDirectory: caches.appendingPathComponent(name),
                          investigationRegistryDirectory: output.appendingPathComponent("registry"))
        }
        let first = engine("first")
        try await measure(first, home: home, label: "cold_actor_os_cache_uncontrolled", sample: 0)
        for sample in 1...5 { try await measure(first, home: home, label: "warm_same_actor", sample: sample) }
        for sample in 1...3 {
            try await measure(engine("fresh-\(sample)"), home: home,
                              label: "fresh_actor_metadata_cold_os_warm", sample: sample)
        }
        let persisted = (FileManager.default.enumerator(at: caches.appendingPathComponent("first"),
            includingPropertiesForKeys: nil)?.allObjects as? [URL] ?? []).contains { $0.pathExtension == "plist" }
        for sample in 1...3 {
            try await measure(engine("first"), home: home,
                label: persisted ? "fresh_actor_persisted_warm_cache" : "fresh_actor_first_cache_unavailable", sample: sample)
        }
    }
    static func main() async {
        do { try await run() }
        catch { fputs("Session catalog replay: \(error)\n", stderr); Darwin.exit(EXIT_FAILURE) }
    }
}
