changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Fixes
      labels: [bug]
    - title: Improvements
      labels: [enhancement]
    - title: Documentation and maintenance
      labels: [documentation, ci, dependencies]
    - title: Other changes
      labels: ['*']
